spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zzb?characterEncoding=utf8&useSSL=true
    username: root
    password: 86931002
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    
mybatis:
   mapperLocations: classpath:mybatis/*Mapper.xml
   typeAliasesPackage: com.example.demo.vo
   configLocation: classpath:/mybatis/config/spring-mybatis.xml
    