spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zzb?characterEncoding=utf8&useSSL=true
    username: root
    password: 86931002
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  redis:
    database: 0  
    host: 192.168.3.14
    port: 6379
    password: zzb
    lettuce:
      pool:
        maxActive: 8
        maxWait: -1
        maxIdle: 8
        minIdle: 0
  rabbitmq:
    host: 
    port: 5672
    username: 
    password:
dubbo:
  application:
    name: provider
    server: true
  registry:
    address: zookeeper://192.168.3.14:2181
  protocol:
    name: dubbo
    port: 20880
  scan: com.example.demo.service
    
mybatis:
  mapperLocations: classpath:mybatis/*Mapper.xml
  typeAliasesPackage: com.example.demo.vo
  configuration: 
    logImpl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapUnderscoreToCamelCase: true
    
#logging:
#  level:
#    com.example.demo.dao: debug

#dubbo provider


    